name: CI/CD Pipeline In Github Actions

on:
  push:
   branches: main

jobs: 
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4
     
     - name: Initilize Repo
       run:  echo "this is my first pipline"

     - name: check the Docker installation
       run:  docker images

     - name: Run Docker Contanier
       run:  docker run hello-world 
       
     
