name: CI/CD Pipeline In Github Actions

on:
  push:
   branches: main

jobs: 
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4
     
     - name: my first stop
       run:  echo "its me pershotamCodes"
     
